version: '3.8'

services:



    bookreview:
        build: BookReviews
        ports:
        - 8000:8000



    postgres:
        image: postgres:14.5
        ports:
        - 5432:5432

        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: pgadmin
            POSTGRES_DB: reviewdb